// Packs the Blender-exported .glb models into one script the game loads
// directly (no file fetching needed — works offline, in Electron and on the web).
//   python blender/build_assets.py   → assets/models/*.glb
//   node tools/pack-models.js        → src/js/render/models-data.js
const fs = require('fs');
const path = require('path');

const DIR = path.join(__dirname, '..', 'assets', 'models');
const OUT = path.join(__dirname, '..', 'src', 'js', 'render', 'models-data.js');
const files = fs.readdirSync(DIR).filter(f => f.endsWith('.glb')).sort();
let out = '// Generated by tools/pack-models.js from assets/models/*.glb (built in Blender by blender/build_assets.py). Do not edit.\n';
out += '(function () {\n  ECHO.MODEL_DATA = {\n';
let total = 0;
for (const f of files) {
  const b = fs.readFileSync(path.join(DIR, f));
  total += b.length;
  out += `    ${JSON.stringify(path.basename(f, '.glb'))}: ${JSON.stringify(b.toString('base64'))},\n`;
}
out += '  };\n})();\n';
fs.writeFileSync(OUT, out);
console.log(`Packed ${files.length} models (${(total / 1024).toFixed(0)} KB) into src/js/render/models-data.js`);
